export const fetchProfileData = () => ({
    firstName: "Idder",
    lastName: "AIT EL MOUDEN",
    currentTotalIncome: 9000,
    goalAmount: 11000,
    incomeSourses: [
        { source: "Salary", amount: 3000 },
        { source: "Freelance", amount: 1500 },
        { source: "Investments", amount: 700 },
        { source: "Other", amount: 300 },
    ],
});

export const fetchTransactionsData = () => [
    {
        category: "Utilitaires",
        consumption: 339,
        budget: 500,
        dateOfCreation: "01/06/2024",
        lastUpdate: "11/06/2024",
        title: "Utility Bill",
        image: null,
    },
    {
        category: "Logement",
        consumption: 500,
        budget: 900,
        dateOfCreation: "01/07/2024",
        lastUpdate: "10/07/2024",
        title: "Housing Rent",
        image: null,
    },
    {
        category: "Alimentation",
        consumption: 50,
        budget: 700,
        dateOfCreation: "01/07/2024",
        lastUpdate: "15/07/2024",
        title: "Groceries",
        image: null,
    },
    {
        category: "Logement",
        consumption: 1000,
        budget: 900,
        dateOfCreation: "01/08/2024",
        lastUpdate: "10/08/2024",
        title: "Housing Rent",
        image: null,
    },
    {
        category: "Transport",
        consumption: 239,
        budget: 600,
        dateOfCreation: "01/08/2024",
        lastUpdate: "20/08/2024",
        title: "Transportation",
        image: null,
    },
    {
        category: "Utilitaires",
        consumption: 100,
        budget: 500,
        dateOfCreation: "01/09/2024",
        lastUpdate: "01/09/2024",
        title: "Utility Bill",
        image: null,
    },
    {
        category: "Alimentation",
        consumption: 150,
        budget: 700,
        dateOfCreation: "01/10/2024",
        lastUpdate: "15/10/2024",
        title: "Groceries",
        image: null,
    },
    {
        category: "Logement",
        consumption: 1200,
        budget: 900,
        dateOfCreation: "01/11/2024",
        lastUpdate: "10/11/2024",
        title: "Housing Rent",
        image: null,
    },
    {
        category: "Transport",
        consumption: 300,
        budget: 600,
        dateOfCreation: "01/11/2024",
        lastUpdate: "20/11/2024",
        title: "Transportation",
        image: null,
    },
    {
        category: "Utilitaires",
        consumption: 150,
        budget: 500,
        dateOfCreation: "01/12/2024",
        lastUpdate: "01/12/2024",
        title: "Utility Bill",
        image: null,
    },
];
